apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: store
        image: elhgawy/store:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: store-service
spec:
  type: NodePort
  selector:
    app: store
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
