# Generated by Django 4.2.7 on 2023-11-26 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderinfo_delete_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.cartitem'),
        ),
    ]
