# Generated by Django 4.2.7 on 2023-11-26 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_orderinfo_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cartitem'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='user_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.useraddress'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='user_visa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.uservisa'),
        ),
    ]
