# Generated by Django 4.2.7 on 2023-11-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_orderinfo_cart_item_orderinfo_cart_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderInfo',
        ),
    ]
