# Generated by Django 4.2.7 on 2023-11-26 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderproducts_orderinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='products',
        ),
    ]
