# Generated by Django 4.2.7 on 2023-11-26 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_orderinfo_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('order_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orderinfo')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orderproducts')),
            ],
        ),
    ]
