# Generated by Django 4.2.7 on 2023-11-27 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0015_alter_orderproducts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='user',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
