# Generated by Django 4.2.7 on 2023-11-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_orderinfo_order_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_products',
            field=models.ManyToManyField(to='store.orderproducts'),
        ),
    ]
